name: YouTube Downloader

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube Video URL'
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install yt-dlp
      run: |
        pip install yt-dlp

    - name: Run yt-dlp
      run: |
        python3 -c "import yt_dlp; yt_dlp.YoutubeDL({'format': 'best', 'quiet': True}).download(['${{ github.event.inputs.url }}'])"
